#!/usr/bin/sh
font="Ubuntu-mono"
URL=https://export.arxiv.org/api/query?search_query=all:

query=`echo | dmenu -p "Search Paper" -fn $font`
query=`echo $query | sed 's/\ /+/g'`

case $query in
    "")
        echo "Program Finished"
        exit
        ;;
    *)
        ;;
esac

result=`curl -s $URL$query"&max_results=50&sortBy=relevance"`
titles="$(echo $result | sed 's#</title>#</title>\n#g' | sed -e 's#.*<title>\(.*\)</title>.*#\1#')"

title=`echo "$titles" \
        | grep -vE '(<summary> |<?xml )' \
        | dmenu -i -p "Papers" -fn $font -l 5`

url=`echo $result \
    | sed -e 's/<title>/\n<title>/g' \
    | grep -e "${title}" \
    | sed -e 's#.*<link href="\(.*\)" rel=.*/>#\1#' \
    | sed -e 's/".*//' \
    | sed -e 's/http/https/' -e 's/abs/pdf/'`

random=$$
pdf_file="/tmp/arxiv_$random.pdf"
curl --compressed "$url.pdf" -o "$pdf_file" && xdg-open $pdf_file
