#!/usr/bin/sh
URL=https://export.arxiv.org/api/query?search_query=all:
query=`echo $* | sed 's/\ /+/g'`

result=`curl -s $URL$query`
titles="$(echo $result | sed 's#</title>#</title>\n#g' | sed -e 's#.*<title>\(.*\)</title>.*#\    \1#')"

echo "Titles"
echo "$titles" | grep -vE '(<summary> |<?xml )'

echo "\nLinks"
echo "$result" \
    | grep -e '<link href' \
    | sed -e 's/<link href=//' -e 's/\ rel.*//' \
    | grep '/abs/' | sed 's/"//g' \
    | sed 's/abs/pdf/'
